name: brother_label_printer
description: Brother printer flutter plugin
version: 0.0.24
author: "developers@purplesoft.io"
homepage: "https://purplesoft.io"

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      android:
        package: io.purplesoft.brother_label_printer
        pluginClass: BrotherLabelPrinterPlugin
      ios:
        pluginClass: BrotherLabelPrinterPlugin